DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE estados (
            id_estado        NUMBER GENERATED BY DEFAULT AS IDENTITY,
            nombre           VARCHAR2(50) NOT NULL,
            descripcion      VARCHAR2(200),
            CONSTRAINT pk_estados PRIMARY KEY (id_estado)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando tabla ESTADOS: ' || SQLERRM);
END;
/
-------------------------------------------------------------

DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE usuarios (
            id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY,
            nombre          VARCHAR2(100) NOT NULL,
            email           VARCHAR2(200) UNIQUE NOT NULL,
            estado          NUMBER NOT NULL,
            fecha_creacion  DATE DEFAULT SYSDATE,
            CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
            CONSTRAINT fk_usuario_estado FOREIGN KEY (estado)
                REFERENCES estados(id_estado)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando tabla USUARIOS: ' || SQLERRM);
END;
/
-------------------------------------------------------------

DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE sesiones (
            id_sesion      NUMBER GENERATED BY DEFAULT AS IDENTITY,
            id_usuario     NUMBER NOT NULL,
            fecha_inicio   DATE DEFAULT SYSDATE,
            fecha_fin      DATE,
            ip_cliente     VARCHAR2(45),
            CONSTRAINT pk_sesiones PRIMARY KEY(id_sesion),
            CONSTRAINT fk_sesion_usuario FOREIGN KEY (id_usuario)
                REFERENCES usuarios(id_usuario)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando tabla SESIONES: ' || SQLERRM);
END;
/
-------------------------------------------------------------

DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE mensajes (
            id_mensaje     NUMBER GENERATED BY DEFAULT AS IDENTITY,
            id_usuario     NUMBER NOT NULL,
            contenido      CLOB NOT NULL,
            fecha_envio    DATE DEFAULT SYSDATE,
            estado         NUMBER NOT NULL,
            CONSTRAINT pk_mensajes PRIMARY KEY(id_mensaje),
            CONSTRAINT fk_msg_usuario FOREIGN KEY (id_usuario)
                REFERENCES usuarios(id_usuario),
            CONSTRAINT fk_msg_estado FOREIGN KEY (estado)
                REFERENCES estados(id_estado)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando tabla MENSAJES: ' || SQLERRM);
END;
/
-------------------------------------------------------------

DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE mensaje_version (
            id_version        NUMBER GENERATED BY DEFAULT AS IDENTITY,
            id_mensaje        NUMBER NOT NULL,
            contenido_anterior CLOB NOT NULL,
            fecha_version     DATE DEFAULT SYSDATE,
            CONSTRAINT pk_msg_version PRIMARY KEY(id_version),
            CONSTRAINT fk_version_msg FOREIGN KEY(id_mensaje)
                REFERENCES mensajes(id_mensaje)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando tabla MENSAJE_VERSION: ' || SQLERRM);
END;
/
-------------------------------------------------------------

DECLARE
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE registro_eventos (
            id_evento     NUMBER GENERATED BY DEFAULT AS IDENTITY,
            id_usuario    NUMBER NOT NULL,
            tipo          VARCHAR2(50),
            mensaje       VARCHAR2(4000),
            fecha         DATE DEFAULT SYSDATE,
            CONSTRAINT pk_registro PRIMARY KEY(id_evento),
            CONSTRAINT fk_registro_usuario FOREIGN KEY(id_usuario)
                REFERENCES usuarios(id_usuario)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error creando tabla REGISTRO_EVENTOS: ' || SQLERRM);
END;
/
